import csv
import io
import os
import shutil
from datetime import datetime
from typing import List, Optional

from src.database import ExpenseRepository, StaffRepository, PaymentMethodRepository
from src.config import CONFIG_DIR
from src.models import Expense


class DataService:
    def __init__(self, expense_repo: ExpenseRepository, staff_repo: StaffRepository):
        self._expense_repo = expense_repo
        self._staff_repo = staff_repo

    def export_csv(self, staff_id: int, filepath: str) -> str:
        expenses = self._expense_repo.get_all(staff_id=staff_id)
        staff = self._staff_repo.get_by_id(staff_id)
        name = staff.name if staff else "Unknown"

        with open(filepath, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["ID", "Staff", "Amount", "Category", "Description", "Date"])
            for e in expenses:
                writer.writerow([e.id, name, e.amount, e.category, e.description, e.expense_date])
        return filepath

    def import_csv(self, staff_id: int, filepath: str) -> int:
        count = 0
        with open(filepath, newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    amount = float(row.get("Amount", 0))
                    category = row.get("Category", "Other")
                    description = row.get("Description", "")
                    date = row.get("Date", datetime.now().strftime("%Y-%m-%d"))
                    self._expense_repo.add(staff_id, amount, category, description, date)
                    count += 1
                except (ValueError, KeyError):
                    continue
        return count

    def export_data(self) -> str:
        backup_dir = os.path.join(CONFIG_DIR, "backups")
        os.makedirs(backup_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_file = os.path.join(backup_dir, f"expenses_backup_{timestamp}.db")
        db_path = os.path.join(CONFIG_DIR, "expenses.db")
        if os.path.exists(db_path):
            shutil.copy2(db_path, backup_file)
        return backup_file

    def list_backups(self) -> List[dict]:
        backup_dir = os.path.join(CONFIG_DIR, "backups")
        if not os.path.exists(backup_dir):
            return []
        backups = []
        for f in sorted(os.listdir(backup_dir), reverse=True):
            path = os.path.join(backup_dir, f)
            if os.path.isfile(path):
                size = os.path.getsize(path)
                backups.append({"name": f, "path": path, "size": size})
        return backups

    def restore_backup(self, backup_path: str) -> bool:
        db_path = os.path.join(CONFIG_DIR, "expenses.db")
        if os.path.exists(backup_path):
            shutil.copy2(backup_path, db_path)
            return True
        return False

    def generate_report_html(self, staff_id: int) -> str:
        stats = self._expense_repo.get_total_stats(staff_id)
        cats = self._expense_repo.get_category_stats(staff_id)
        staff = self._staff_repo.get_by_id(staff_id)
        name = staff.name if staff else "Staff"

        cat_rows = "".join(
            f"<tr><td>{c.category}</td><td>${c.total:.2f}</td>"
            f"<td>{c.count}</td><td>${c.avg:.2f}</td></tr>"
            for c in cats
        )

        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Expense Report - {name}</title>
<style>
body {{ font-family: Arial; max-width: 800px; margin: auto; padding: 20px; }}
h1 {{ color: #333; }}
table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }}
th {{ background: #4CAF50; color: white; }}
.summary {{ background: #f5f5f5; padding: 15px; border-radius: 5px; }}
</style></head><body>
<h1>Expense Report — {name}</h1>
<div class="summary">
<p><strong>Total Spent:</strong> ${stats.total_amount:.2f}</p>
<p><strong>Transactions:</strong> {stats.total_expenses}</p>
<p><strong>Average:</strong> ${stats.avg_amount:.2f}</p>
<p><strong>Period:</strong> All time</p>
</div>
<h2>Category Breakdown</h2>
<table><tr><th>Category</th><th>Total</th><th>Count</th><th>Average</th></tr>{cat_rows}</table>
<p><em>Generated by Smart Expense Tracker on {datetime.now().strftime("%Y-%m-%d %H:%M")}</em></p>
</body></html>"""
        return html
