from fastapi import APIRouter, Header, Request
from fastapi.responses import HTMLResponse
from typing import Optional

from src.auth.middleware import verify_token
from src.database import ExpenseRepository, StaffRepository

router = APIRouter()


def _require_auth(authorization: Optional[str]):
    if not authorization:
        from fastapi import HTTPException
        raise HTTPException(status_code=401, detail="Not authenticated")
    user = verify_token(authorization.replace("Bearer ", ""))
    if not user:
        from fastapi import HTTPException
        raise HTTPException(status_code=401, detail="Invalid token")
    return user


@router.get("/monthly")
def monthly_report(request: Request, authorization: Optional[str] = Header(None), staff_id: Optional[int] = None):
    user = _require_auth(authorization)
    db = request.app.state.db
    expense_repo = ExpenseRepository(db)
    staff_repo = StaffRepository(db)
    sid = staff_id or user.staff_id
    staff = staff_repo.get_by_id(sid)
    expenses = expense_repo.get_all(staff_id=sid, sort_by="date_desc")
    total = expense_repo.get_total_stats(sid)
    cats = expense_repo.get_category_stats(sid)

    staff_name = staff.name if staff else "Staff #" + str(sid)
    cat_rows = "".join(
        f"<tr><td>{c.category}</td><td>{c.count}</td><td>{c.total:.2f}</td>"
        f"<td>{c.budget:.2f}</td><td>{c.budget_pct:.1f}%</td></tr>"
        for c in cats
    )
    exp_rows = "".join(
        f"<tr><td>{e.expense_date}</td><td>{e.category}</td>"
        f"<td>{e.amount:.2f}</td><td>{e.description}</td></tr>"
        for e in expenses[:100]
    )
    html = f"""<!DOCTYPE html>
<html><head><title>Report - {staff_name}</title>
<style>
body{{font-family:sans-serif;margin:20px;color:#1e293b}}
table{{border-collapse:collapse;width:100%}}
th,td{{border:1px solid #e2e8f0;padding:8px;text-align:left}}
th{{background:#f1f5f9;font-size:.85rem}}
h1{{font-size:1.3rem}}h2{{font-size:1.1rem;margin-top:24px}}
.summary{{display:flex;gap:16px;margin:16px 0}}
.stat{{background:#f1f5f9;padding:12px 20px;border-radius:8px;text-align:center}}
.stat .val{{font-size:1.5rem;font-weight:700}}.stat .lbl{{font-size:.8rem;color:#64748b}}
@media print{{body{{margin:10px}}}}
</style></head>
<body>
<h1>Monthly Expense Report</h1>
<p><strong>{staff_name}</strong> | {staff.department if staff else ""}</p>
<div class="summary">
<div class="stat"><div class="val">{total.total_expenses}</div><div class="lbl">Expenses</div></div>
<div class="stat"><div class="val">{total.total_amount:.2f}</div><div class="lbl">Total Spent</div></div>
<div class="stat"><div class="val">{total.avg_amount:.2f}</div><div class="lbl">Average</div></div>
</div>
<h2>By Category</h2>
<table><tr><th>Category</th><th>Count</th><th>Total</th><th>Budget</th><th>Used</th></tr>{cat_rows}</table>
<h2>Expenses (up to 100)</h2>
<table><tr><th>Date</th><th>Category</th><th>Amount</th><th>Description</th></tr>{exp_rows}</table>
<p style="margin-top:24px;color:#64748b;font-size:.8rem">Generated by Smart Expense Tracker</p>
</body></html>"""
    return HTMLResponse(content=html)
